ceilings/urls.py
from django.conf.urls import patterns, url
from ceilings import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\w+)/$', views.detail, name='detail'),
)

gallery/urls.py
from django.conf.urls import patterns, url
from gallery import views


urlpatterns = patterns('',
    url(r'^$', views.GalleryView.as_view(), name='gallery'),
    url(r'^(?P<pk>\w+)/$', views.detail, name='picture'),
)

potolki/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from potolki import views
from home.views import FeedbackView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
	url(r'^contact/$', views.ContactView.as_view(), name='contact'),
	url(r'^ceilings/', include('ceilings.urls', namespace="ceilings")),
	url(r'^prices/', include('prices.urls', namespace="prices")),
	url(r'^calculator/', include('calculator.urls', namespace="calculator")),
	url(r'^gallery/', include('gallery.urls', namespace="gallery")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prices/urls.py
from django.conf.urls import patterns, url
from prices import views


urlpatterns = patterns('',
    url(r'^$', views.PriceView.as_view(), name='price'),
)

gallery/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Gallery(models.Model):
	name = models.CharField(verbose_name='Название раздела галереи.', max_length=255)
	title = models.TextField()
	image = models.ImageField(blank=True, upload_to='gallery/', help_text='Картинка которая в галерее.', verbose_name='Ссылка картинки')
	slug = models.SlugField(max_length=100, verbose_name=u'URL категории', unique=True, help_text='Введите URL без "/" и пробелов.')
	
	def __unicode__(self):
		return self.name
		
		
class Picture(models.Model):
	image = models.ImageField(blank=True, upload_to='gallery/pictures/', verbose_name='Размер картинки 780x560px')
	gallery = models.ForeignKey(Gallery)
	order = models.PositiveIntegerField(null=True)
	

gallery/views.py
from django.views.generic import TemplateView
from gallery.models import Gallery, Picture
from django.views.generic.detail import DetailView
from ceilings.models import Ceiling
from django.shortcuts import render


class GalleryView(TemplateView):
    template_name = 'gallery/gallery.html'
    
    def get_context_data(self, **kwargs):
        context = super(GalleryView, self).get_context_data(**kwargs)
        context['gallerys'] = Gallery.objects.all()
        context['ceilings'] = Ceiling.objects.all()
        return context
        
def detail(request, pk):
	ceilings = Ceiling.objects.all()
	pictures = Picture.objects.filter(gallery__slug=pk)
	title = Gallery.objects.get(slug=pk)

	return render(request, 'gallery/picture.html', {'pictures': pictures, 'ceilings': ceilings, 'title': title})
        
'''       
class PictureDetailView(DetailView):
	model = Gallery
	template_name = 'gallery/picture.html'
	
	def get_context_data(self, **kwargs):
		context = super(PictureDetailView, self).get_context_data(**kwargs)
		context['pictures'] = Picture.objects.filter(gallery = self.object)
		context['ceilings'] = Ceiling.objects.all()
		return context
'''

templates/gallery/gallery.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ГАЛЕРЕЯ{% endblock title %}


{% block nav_class_gallery %}selected{% endblock nav_class_gallery %}


{% block nav_potolok %}
                    <ul>{% for ceiling in ceilings %}
                        <li><a href="{% url 'ceilings:detail' ceiling.slug %}">{{ ceiling.name }}</a></li>
                        {% endfor %}
      				</ul>
{% endblock nav_potolok %}


{% block content %}

<div id="tooplate_header">
	<div id="tooplate_main">
		<ul class="grid">
			{% for gallery in gallerys %}
            <div class="gallery_box no_margin_right">
            	<a href="{% url 'gallery:picture' gallery.slug %}" ><h4><strong>{{ gallery.name }}</strong></h4></a>
                <div id="portfolio_1" class="image_frame image_fl"><span></span><a href="{% url 'gallery:picture' gallery.slug %}" ><img src="{{ gallery.image.url }}" width="250" height="250" /></a></div>
			</div>
            {% endfor %}
            </ul>
            <div class="cleaner"></div>
            
	</div><!-- end of main -->   
   </div> <!-- end of header -->
{% endblock content %}

templates/gallery/picture.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title.title }}{% endblock title %}


{% block script %}<script src="{% static 'js/prototype.js' %}" type="text/javascript"></script>{% endblock script %}


{% block nav_potolok %}
                    <ul>{% for ceiling in ceilings %}
                        <li><a href="{% url 'ceilings:detail' ceiling.slug %}">{{ ceiling.name }}</a></li>
                        {% endfor %}
      				</ul>
{% endblock nav_potolok %}


{% block content %}

<div id="tooplate_header">
	<div id="tooplate_main">
		<ul class="grid">
				<div id="portfolio_1" class="image_frame image_fl"><span></span><a href="{% url 'gallery:gallery' %}" ><img src="{% static 'images/7c519ca3b4e729d65dcf96fe0a90d154.jpg' %}" width="130" height="130" alt="Назад" /></a></div>
			{% for picture in pictures %}        
                <div id="portfolio_1" class="image_frame image_fl"><span></span><a href="{{ picture.image.url }}" rel="lightbox[portfolio]"><img src="{{ picture.image.url }}" width="130" height="130" alt="" /></a></div>
            {% endfor %}
            </ul>
            <div class="cleaner"></div>
            
	</div><!-- end of main -->   
   </div> <!-- end of header -->
{% endblock content %}