calculator/urls.py
from django.conf.urls import patterns, url
from calculator import views


urlpatterns = patterns('',
    url(r'^$', views.calculator, name='calculator'),
)

ceilings/urls.py
from django.conf.urls import patterns, url
from ceilings import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\w+)/$', views.detail, name='detail'),
)

gallery/urls.py
from django.conf.urls import patterns, url
from gallery import views


urlpatterns = patterns('',
    url(r'^$', views.GalleryView.as_view(), name='gallery'),
    url(r'^(?P<pk>\w+)/$', views.detail, name='picture'),
)

potolki/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from potolki import views
from home.views import FeedbackView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
	url(r'^contact/$', views.ContactView.as_view(), name='contact'),
	url(r'^ceilings/', include('ceilings.urls', namespace="ceilings")),
	url(r'^prices/', include('prices.urls', namespace="prices")),
	url(r'^calculator/', include('calculator.urls', namespace="calculator")),
	url(r'^gallery/', include('gallery.urls', namespace="gallery")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prices/urls.py
from django.conf.urls import patterns, url
from prices import views


urlpatterns = patterns('',
    url(r'^$', views.PriceView.as_view(), name='price'),
)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}{% endblock title %}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link type="image/png" rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
<link href="{% static 'css/tooplate_style.css' %}" rel="stylesheet" type="text/css" />

<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>

<link rel="stylesheet" type="text/css" href="{% static 'css/ddsmoothmenu.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}" />

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ddsmoothmenu.js' %}">

</script>

<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "tooplate_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>

<script src="{% static 'js/jquery-1.2.6.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.kwicks-1.5.1.pack.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.kwicks-1.5.1.js' %}" type="text/javascript"></script>
{% block script %}{% endblock script %}
<script src="{% static 'js/scriptaculous.js' %}" type="text/javascript"></script>
<script src="{% static 'js/lightbox.js' %}" type="text/javascript"></script>
<script src="{% static 'js/builder.js' %}" type="text/javascript"></script>
<script src="{% static 'js/effects.js' %}" type="text/javascript"></script>


<script type="text/javascript">
	$().ready(function() {
		$('.slider').kwicks({
			max : 740,
			spacing : 1
		});
	});
</script>

</head>
<body>
<div id="liniya">
<div id="logo_top"><span></span><a href="{% url 'index' %}" ><img src="{% static 'images/Cool-Text-160987126323701.png' %}" width="322" height="125" /></a></div>
<div class="customhead_tel">
            <table border="0" style="width: 553px;">
                <tbody>
                    <tr>
                        <td>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;"><span>(057)</span></span><span style="color:#2E2E2E;"> 771-45-20</span></p></h4>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(063)</span><span style="color:#2E2E2E;"> 291-41-67</span></p></h4>
                        </td>
                        <td>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(063)</span>&nbsp;<span style="color:#2E2E2E;">831-72-28</span></p></h4>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(050)</span><span style="color:#2E2E2E;"> 225-61-03</span></p></h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            <span style="font-family:arial,helvetica,sans-serif;font-variant: small-caps;"><span style="font-size:24px;"><span style="color:#dd4528;">Email: </span><span style="color:#2E2E2E;">orfi@gmail.com</span></span>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <p>
                &nbsp;</p>
        </div>
        </div>
        </div>
<div id="tooplate_top_wrapper">
	<div id="tooplate_top">
    	<div id="tooplate_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="{% url 'index' %}" class="{% block nav_class_index %}{% endblock nav_class_index %}"><span></span>ГЛАВНАЯ</a></li>
                <li><a href="{% url 'gallery:gallery' %}" class="{% block nav_class_gallery %}{% endblock nav_class_gallery %}"><span></span>ГАЛЕРЕЯ</a></li>
                <li><a href="#"><span></span>О ПОТОЛКАХ</a>
                {% block nav_potolok %}{% endblock nav_potolok %}</li>
              <li><a href="#"><span></span>РАСЧЕТ СТОИМОСТИ</a>
              		<ul>
                        <li><a href="{% url 'prices:price' %}">ПРАЙС-ЛИСТ</a></li>
                        <li><a href="{% url 'calculator:calculator' %}">КАЛЬКУЛЯТОР ЦЕН</a></li>			
                    </ul>
              </li>
              <li><a href="{% url 'contact' %}" class="{% block nav_class_contact %}{% endblock nav_class_contact %}"><span></span>КОНТАКТЫ</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of menu -->
    </div> <!-- end of top -->
</div> <!-- end of top wrapper -->
{% block content %}
{% endblock content %}
<div class="cleaner"></div>
    </div> <!-- end of main -->
</div> <!-- end of main wrapper -->

<div id="tooplate_footer_wrapper">
	<div id="tooplate_footer">
    	<a href="#tooplate_header" class="goto_top"></a>
    	<div class="col_3">
        	<h5>Контакты</h5>
            <div class="rp_pp">
            	<div class="solo"><a href="{% url 'contact' %}"><img src="{% static 'images/DMyuLdBw_inettools.net_resize_image.jpg' %}" alt="image" /></a></div>

            <strong>Life:</strong><a href="{% url 'contact' %}"> (063) 291-41-67</a></br>
            <strong>Life:</strong><a href="{% url 'contact' %}"> (063) 831-72-29</a><br />
            <strong>MTC:</strong><a href="{% url 'contact' %}"> (050) 225-61-03</a><br />
            <strong>Phone:</strong><a href="{% url 'contact' %}"> (057) 771-45-20</a>           
            </div>
            <div class="cleaner"></div>
            <div class="rp_pp">
            	<div class="solo"><a href="{% url 'contact' %}"><img src="{% static 'images/JEoW08Oh_inettools.net_resize_image.jpg' %}" alt="image" /></a></div>

               </br><strong>Email:</strong> <a href="mailto:orfi@gmail.com">orfi@gmail.com</a>
               <div class="cleaner"></div> 
            </div> 
    	</div>
        <div class="col_3">
        	<div id="site_title"><h1><a href="{% url 'index' %}"></a></h1></div>          
        </div>
        <div class="col_3 no_margin_right">
			<h5>О нас</h5>
            <p><em>Компания Орфи специализируется на изготовлении и установке натяжных потолков в Харькове. Цены на натяжные потолки у нашей компании находятся на среднем уровне, для изготовления мы используем только высококачественную пленку бельгийского, французского и немецкого производства.</em></p>
            <p>© 2016 <a href="#">Орфи</a><br />
			<div class="cleaner h10"></div>
		      <a href="#"><img alt="vk" src="{% static 'images/vk.jpg' %}" title="vkontakte" /></a>
              <a href="#"><img alt="facebook" src="{% static 'images/facebook.png' %}" title="facebook" /></a>
              <a href="#"><img alt="twitter" src="{% static 'images/twitter.png' %}" title="twitter" /></a>
              <a href="#"><img alt="youtube" src="{% static 'images/youtube.png' %}" title="youtube" /></a>                 		
        </div>
        <div class="cleaner"></div>
    </div> <!-- end of footer -->
</div> <!-- end of footer wrapper -->
</body>
</html>

templates/contact.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}КОТАКТЫ{% endblock title %}


{% block nav_class_contact %}selected{% endblock nav_class_contact %}


{% block nav_potolok %}
                    <ul>{% for ceiling in ceilings %}
                        <li><a href="{% url 'ceilings:detail' ceiling.slug %}">{{ ceiling.name }}</a></li>
                        {% endfor %}
      				</ul>
{% endblock nav_potolok %}


{% block content %}



<div id="tooplate_main_wrapper">
	<div id="tooplate_main">
		<div id="content">
        	
            <h2>Наши Контакты</h2>
                <p>Получите удовольствие и комфорт от покупки. Основным отличием нашей компании является - индивидуальный подход к каждому клиенту.</p>
               
                
                <div class="col_3 float_l">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2565.9207670864494!2d36.24584095081923!3d49.97534442926456!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4127a07d4e981817%3A0x4f6c3cac75d936cc!2z0LLRg9C7LiDQk9C-0LvRjNC00LHQtdGA0LPRltCy0YHRjNC60LAsIDExLCDQpdCw0YDQutGW0LIsINCl0LDRgNC60ZbQstGB0YzQutCwINC-0LHQu9Cw0YHRgtGM!5e0!3m2!1sru!2sua!4v1454327866073" width="280" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
               		
                    
                </div>
                <div class="col_3 float_r no_margin_right">
                	<h4>Телефоны</h4>
                	<h6><strong>Специалист отдела продаж: Александра</strong></h6></br>                   
                    <strong>Life:</strong> (063) 291-41-67</br></br>
                    <strong>Life:</strong> (063) 831-72-29<br /></br>
                    <strong>MTC:</strong> (050) 225-61-03<br /></br>
                    <strong>Phone:</strong> (057) 771-45-20<br /></br>
                    <strong>Email:</strong> <a href="mailto:orfi@gmail.com">orfi@gmail.com</a>                     
                </div>
            <div class="cleaner"></div>
        </div>
        <div id="sidebar">
			<div class="cleaner h40"></div>
            <em><h3>Возможные идеи для вашего дома</h3></em>
            <ul class="flickr_stream">
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/1.jpg' %}" width="75" height="75" alt="Flickr 01" /></a></li>
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/2.jpg' %}" width="75" height="75" alt="Flickr 02" /></a></li>
                <li class="no_margin_right"><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/3.png' %}" width="75" height="75" alt="Flickr 03" /></a></li>
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/4.jpg' %}" width="75" height="75" alt="Flickr 04" /></a></li>
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/5.jpg' %}" width="75" height="75" alt="Flickr 05" /></a></li>
                <li class="no_margin_right"><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/6.jpg' %}" width="75" height="75" alt="Flickr 06" /></a></li>
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/7.jpg' %}" width="75" height="75" alt="Flickr 07" /></a></li>
                <li><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/8.jpg' %}" width="75" height="75" alt="Flickr 08" /></a></li>
                <li class="no_margin_right"><a href="{% url 'gallery:gallery' %}"><img src="{% static 'images/9.jpg' %}" width="75" height="75" alt="Flickr 09" /></a></li>
            </ul>
        </div> <!-- end of sidebar -->
{% endblock content %}

templates/feedback.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" class="no-js">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Вызов Технолога</title>
<link type="image/png" rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link href="{% static 'css/tooplate_style.css' %}" rel="stylesheet" type="text/css" />

<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>

<link rel="stylesheet" type="text/css" href="{% static 'css/ddsmoothmenu.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}" />

<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/highlight.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ddsmoothmenu.js' %}">

</script>

<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "tooplate_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>
<script type="text/javascript">
	$().ready(function() {
		$('.slider').kwicks({
			max : 740,
			spacing : 1
		});
	});
</script>
</head>

<body>

<div id="liniya">
<div id="logo_top"><span></span><a href="{% url 'index' %}" ><img src="{% static 'images/Cool-Text-160987126323701.png' %}" width="322" height="125" /></a></div>
<div class="customhead_tel">
            <table border="0" style="width: 553px;">
                <tbody>
                    <tr>
                        <td style="width: 228px;">
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;"><span>(057)</span></span><span style="color:#2E2E2E;"> 771-45-20</span></p></h4>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(063)</span><span style="color:#2E2E2E;"> 291-41-67</span></p></h4>
                        </td>
                        <td style="width: 309px;">
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(063)</span>&nbsp;<span style="color:#2E2E2E;">831-72-28</span></p></h4>
                            <h4><p style="text-align: center;">
                                <span style="color:#dd4528;">(099)</span><span style="color:#2E2E2E;"> 225-61-03</span></p></h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="width: 543px; text-align: center;">
                            <span style="font-family:arial,helvetica,sans-serif;font-variant: small-caps;"><span style="font-size:24px;"><span style="color:#dd4528;">Email: </span><span style="color:#2E2E2E;">orfi@gmail.com</span></span>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <p>
                &nbsp;</p>
        </div>
        </div>
        </div>
<div id="tooplate_top_wrapper">
	<div id="tooplate_top">
    	<div id="tooplate_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="{% url 'index' %}" class="{% block nav_class_index %}{% endblock nav_class_index %}"><span></span>ГЛАВНАЯ</a></li>
                <li><a href="{% url 'gallery:gallery' %}" class="{% block nav_class_gallery %}{% endblock nav_class_gallery %}"><span></span>ГАЛЕРЕЯ</a></li>
                <li><a href="#"><span></span>О ПОТОЛКАХ</a>
                <ul>{% for ceiling in ceilings %}
                        <li><a href="{% url 'ceilings:detail' ceiling.slug %}">{{ ceiling.name }}</a></li>
                        {% endfor %}
      				</ul>
                </li>
              <li><a href="#"><span></span>РАСЧЕТ СТОИМОСТИ</a>
              		<ul>
                        <li><a href="{% url 'prices:price' %}">ПРАЙС-ЛИСТ</a></li>
                        <li><a href="{% url 'calculator:calculator' %}">КАЛЬКУЛЯТОР ЦЕН</a></li>			
                    </ul>
              </li>
              <li><a href="{% url 'contact' %}" class="{% block nav_class_contact %}{% endblock nav_class_contact %}"><span></span>КОНТАКТЫ</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of menu -->
    </div> <!-- end of top -->
</div> <!-- end of top wrapper -->
<div id="kartinka"><img src="{% static 'images/0_9ef7b_1bcdd104_L.png' %}" /></div>
	<div id="page-wrap">
	<h3><center>Вызов технолога</center></h3></br>
	<p>* обязательные поля</p>
	{% if form.errors %}
        <p style="color: red;">
            Заполните пожалуйста правильно поля!
            {{ form.name.errors }}
            {{ form.phone.errors }}
        </p>
    {% endif %}
		<form id="myform" method="post">
			{% csrf_token %}
			<div>
			<div class="field">
				<label for="{{ id_name }}" >* Ваше Имя</label>
				<input class="inputfield textfield" {{ form.name }} 
			</div>
			<div class="field">				
				<label for="{{ id_phone }}" >* Ваш Номер</label>
				<input class="inputfield textfield" {{ form.phone }} 
			</div>
			
			<div class="field area">
				<label for="{{ id_message }}" >Сообщение</label>
				<textarea class="inputfield textarea1" {{ form.message }} </textarea>
			</div>
			</div>
			<!--div class="clear"></div-->
			<input class="submitbutton" type="submit" value="Отправить" />

		</form>
	</div>

</body>

</html>

templates/index.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{% for item in home %}{{item.title}}{% endfor %}{% endblock title %}


{% block nav_class_index %}selected{% endblock nav_class_index %}


{% block nav_potolok %}
                    <ul>{% for ceiling in ceilings %}
                        <li><a href="{% url 'ceilings:detail' ceiling.slug %}">{{ ceiling.name }}</a></li>
                        {% endfor %}
      				</ul>
{% endblock nav_potolok %}


{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><strong>{{ message }}</strong></li>
    {% endfor %}
</ul>
{% endif %}

<div id="tooplate_header_wrapper">
	<div id="tooplate_header">
    
    	<div id="site_title"><h1><a href="{% url 'index' %}">Натяжные потолки ОРФИ</a></h1></div>
        
        <div id="slider_wrapper">
            <ul class="slider horizontal" >
            {% for slider in sliders %}
                <li><img src="{{ slider.image.url }}" width="920" height="330" alt="Slider" /></li>
            {% endfor %}    
            </ul>
		</div>
    </div> <!-- end of header -->
</div> <!-- end of header wrapper -->

<div id="tooplate_main_wrapper">
	<div id="tooplate_main">
    	<div id="content_top">
            <div class="post col_2 no_bottom float_l">
                <h2><a href="{% url 'feedback' %}">ВЫЗОВ ТЕХНОЛОГА</a></h2></br>
                <div class="solo"><span></span><a href="{% url 'feedback' %}"><img class="myclass" src="{% static 'images/zamer.png' %}" alt="Image 01" /></a></div>
                <p>Монтаж натяжного потолка рекомендуется выполнять на завершающем этапе ремонтных работ. Данный вид отделки потолка занимает от 3х часов до нескольких дней в зависиости от конфигурации и сложности дизайна.</p>
                <div class="cleaner"></div>
            </div>
            <div class="post col_2 no_bottom float_r">
                <h2><a href="{% url 'calculator:calculator' %}">КАЛЬКУЛЯТОР</a></h2></br>               
                <div class="solo"><span></span><a href="{% url 'calculator:calculator' %}"><img class="myclass_2" src="{% static 'images/kalculator.png' %}" alt="Image 02" /></a></div>
                <p>Но помните, что этот просчет будет предварителен. Т.к. каждый потолок индивидуален и зависит от многих факторов - размеров помещения, выбранных материалов, геометрии потолка, осветительных приборов и т.д. Поэтому более точная стоимость натяжного потолка может быть определена только технологом после осмотра и замера помещения.</p>
                <div class="cleaner"></div>
            </div>
            <div class="cleaner"></div>
        </div>
        
		<div id="content">
                
            <div class="col_3">
                <em><h3>Наши преимущества!</h3></em>
                <ul class="tooplate_list">
                	<li>ВЫГОДНО</li>
                    <li>БЫСТРО</li>
                    <li>ПРАКТИЧНО</li>
                    <li>НАДЕЖНО</li>
                    <li>КРАСИВО</li>
                    <li>ДОЛГОВЕЧНО</li>
                </ul>
            </div>
            <div class="col_3 no_margin_right">
                <p class="testimonial"><em>Фото натяжных потолков разных цветов и фактур представлены в галерее наших работ.</em></p></br>  
                <p class="testimonial"><em>Получите удовольствие и комфорт от покупки.</em></p></br>
                <p class="testimonial"><em>Специалисты самостоятельно приедут к Вам на объект и сделают презентацию пленки.</em></p>
			</div>
            <div class="cleaner"></div>
        </div>
        <div id="sidebar">
                           
            <em><h3>Как к нам проехать</h3></em>
			<div class="solo"><span></span><a href="{% url 'contact' %}"><img class="myclass_3" src="{% static 'images/1_2851.png' %}" width="256" height="152" alt="Map" /></a></div>
        </div> <!-- end of sidebar -->
{% endblock content %}